create database WebMayAnh
GO


Use WebMayAnh
Go

----tạo bảng ----
-----NHÂN VIÊN ---------
CREATE TABLE NHANVIEN (
     IDNV INT identity,
	 TENNV NVARCHAR (100),
	 SDT INT,
	 TAIKHOAN VARCHAR(100) ,
	 MATKHAU NVARCHAR (100)
	 )
--------KHÁCH HÀNG ---------
CREATE TABLE KHACHHANG (
      IDKH INT identity ,
	  TENKH NVARCHAR (100),
	  SDT INT ,
	  EMAIL NVARCHAR (100),
	  DIACHI NVARCHAR(100),
	  TAIKHOAN VARCHAR(100),
	  MATKHAU NVARCHAR (100)
	  )
------ MÁY ẢNH ----------
CREATE TABLE MAYANH (
    IDMAY INT identity,
	TENMAY NVARCHAR (100),
	HINHANH VARCHAR (300),
	MOTA NVARCHAR(300),
	DONGIA INT,
	IDLOAIMAY INT
	)
-------LOAI MÁY----------
CREATE TABLE LOAIMAY (
     IDLOAIMAY INT identity,
	 TENLMAY NVARCHAR (100)
	 )
-------ĐƠN HÀNG -------
CREATE TABLE DONHANG (
      IDDONHANG INT identity,
	  IDKH INT ,
	  NGAYLAP DATE,
	  GHICHU NVARCHAR (300)
	  )
------CT ĐƠN HÀNG -------
CREATE TABLE CTDONHANG (
     IDCTDONHANG INT identity ,
	 IDDONHANG INT ,
	 IDMAY INT ,
	 DONGIA INT ,
	 SOLUONG INT 
	 )
-------- TẠO KHÓA CHÍNH -----------
 ALTER TABLE [dbo].[NHANVIEN] ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY(IDNV)
 ALTER TABLE [dbo].[KHACHHANG] ADD CONSTRAINT PK_KHACHHANG PRIMARY KEY (IDKH)
 ALTER TABLE [dbo].[MAYANH] ADD CONSTRAINT PK_MAYANH PRIMARY KEY (IDMAY)
 ALTER TABLE [dbo].[LOAIMAY] ADD CONSTRAINT PK_LOAIMAY PRIMARY KEY (IDLOAIMAY)
 ALTER TABLE [dbo].[DONHANG] ADD CONSTRAINT PK_DONHANG PRIMARY KEY (IDDONHANG)
 ALTER TABLE [dbo].[CTDONHANG] ADD CONSTRAINT PK_CTDONHANG PRIMARY KEY (IDCTDONHANG)
 ---- kháo ngoại ---
ALTER TABLE [dbo].[DONHANG] ADD CONSTRAINT FK_donhang_IDKH FOREIGN KEY(IDKH) REFERENCES[dbo].[KHACHHANG](IDKH)
ALTER TABLE [dbo].[CTDONHANG] ADD CONSTRAINT FK_CTDONHANG_IDDH FOREIGN KEY(IDDONHANG) REFERENCES [dbo].[DONHANG](IDDONHANG)
ALTER TABLE [dbo].[CTDONHANG] ADD CONSTRAINT FK_CTDONHANG_IDMAY FOREIGN KEY(IDMAY) REFERENCES [dbo].[MAYANH](IDMAY)
ALTER TABLE [dbo].[MAYANH] ADD CONSTRAINT FK_IDLAOIANH_IDMAY FOREIGN KEY(IDLOAIMAY) REFERENCES [dbo].[LOAIMAY](IDLOAIMAY)
